//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace NAA.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NAA_User_Profile
    {
        public int ApplicantID { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "This field is required")]
        public string ApplicantName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DisplayName("Address")]
        public string ApplicantAddress { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "This field is required and cannot have spaces")]
        [MinLength(11, ErrorMessage = "This has to be a correct phone number!")]
        [MaxLength(11, ErrorMessage = "This has to be a correct phone number!")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [EmailAddress(ErrorMessage = "This has to be a real email address" )]
        public string Email { get; set; }
        public string UserID { get; set; }
    }
}
